language: python

python:
  - "3.9"

jobs:
  include:
    - stage: "Build Lab 2."
      name: "Run tests for Lab 2"
      python: 3.9
      install:
        - cd ./lab2/
        - make install
        - make run
        - make deploy
      script: make test || true
    - stage: "Build Lab 4."
      name: "Build Docker images & Home task"
      services:
        - docker
      install:
        - cd ./lab4/
      script:
        -- docker build -t vitaliykuz/lab4_bobas:django-travis-monitoring -f Dockerfile.monitoring .
        - docker images
        - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin; vitaliykuz/lab4_bobas:django-travis-monitoring; else echo "PR skip deploy"; fi
        - docker build -t vitaliykuz/lab4_bobas:django-travis -f Dockerfile .
        - docker images
        - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin; vitaliykuz/lab4_bobas:django-travis; else echo "PR skip deploy"; fi
    - stage: "Build Lab 5."
      name: "Build and run Docker images via make"
      services:
        - docker
      install:
        - cd ./lab5/
        - make app
        - make tests
      script:
        - make run
        - make test-app
        - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin; fi
        -make push
branches:
  only:
    - master